[package]
name = "hyppos-service"
version = "0.1.0"
authors = ["Sergey Noskov <albibek@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
url = "2.1.1"
serde = { version = "1.0.115", features = ["derive"] }
thiserror = "1.0.20"
reqwest = { version = "0.10.8", features = ["json"] }
base64 = "0.12.3"
